#!/usr/bin/env python3
import sys
import random

HAPPY_WORDS = [
    "happy",
    "cute",
    "exciting",
    "fun",
    "oopsy",
    "可愛い",
    "おいしい",
]

BORING_WORDS = [
    "legacy",
    "regression",
    "bug",
    "typo",
    "crash",
    "update",
    "deprecation",
    "bump",
]

BORED_EMOJI = [
    r"(´-ω-`)",
    r"(‾̀ _ ‾̀ )",
    r"(／ˍ・、)",
    r"(ᴗ˳ᴗ)",
    r"(っ˘̩╭╮˘̩)っ",
    r"🥱",
    r"*zzzzz*",
]

SAD_EMOJI = [
    r"(ノ_ <。)",
    r"(ﾉД`)",
    r".・゜゜・（／。＼）・゜゜・．",
    r"(゜´Д｀゜)",
    r"(๑´╹‸╹`๑)",
]


def is_suitably_exotic(commit_subject: str) -> bool:
    exotic_letter_count = 0
    for letter in commit_subject:
        if ord(letter) > 255:
            exotic_letter_count += 1

    return exotic_letter_count / len(commit_subject) > 0.1


def does_contains_word_in_list(word_list: list[str], commit_subject: str) -> bool:
    lowercase_commit_subject = commit_subject.lower()
    for word in word_list:
        if word in lowercase_commit_subject:
            return True
    return False


def verify_legal_commit_subject(commit_subject: str) -> bool:
    if not is_suitably_exotic(commit_subject):
        print(f"ASCII is boring {random.choice(BORED_EMOJI)}", file=sys.stderr)
        print(f"🎯 try something fun instead", file=sys.stderr)
        return False
    if not does_contains_word_in_list(HAPPY_WORDS, commit_subject):
        print(f"Why so sad {random.choice(SAD_EMOJI)}???", file=sys.stderr)
        print("🎯 More happy words pls", file=sys.stderr)
        return False
    if does_contains_word_in_list(BORING_WORDS, commit_subject):
        print(
            f"Ok boomer, go back to IBM {random.choice(BORED_EMOJI)}!!",
            file=sys.stderr,
        )
        print("🎯 Less tryhard speak thx", file=sys.stderr)
        return False

    return True


def remove_comments_from_commit(commit_message: list[str]) -> list[str]:
    return [line for line in commit_message if len(line) > 0 and line[0] != "#"]


if __name__ == "__main__":
    commit_message_file = sys.argv[1]
    whole_commit_message = open(commit_message_file, "r").readlines()
    commit_message = remove_comments_from_commit(whole_commit_message)

    if not verify_legal_commit_subject(commit_message[0]):
        print(f"\nCommit vibe-check failed {random.choice(SAD_EMOJI)}!")
        exit(1)
